import test from 'node:test'
import assert from 'node:assert/strict'
import {qualifyFleet, scenarios} from '../workload/fleet-qualification.mjs'

const cases = {baseline: ['QUALIFIED_REHEARSAL', 'REHEARSAL'], stale_quote: ['REFUSE_PROMOTION', 'tdx-b:STALE_QUOTE'], revoked_node: ['REFUSE_PROMOTION', 'tdx-c:REVOKED'], policy_skew: ['REFUSE_PROMOTION', 'tdx-b:POLICY_SKEW'], verifier_partition: ['REFUSE_PROMOTION', 'tdx-a:VERIFIER_UNAVAILABLE'], kbs_partition: ['REFUSE_PROMOTION', 'tdx-a:KBS_UNAVAILABLE'], capacity_exceeded: ['REFUSE_PROMOTION', 'CAPACITY_LIMIT_ENFORCED'], false_live_claim: ['REFUSE_PROMOTION', 'FALSE_LIVE_CLAIM']}
for (const [name, [decision, reason]] of Object.entries(cases)) test(`${name} produces a fail-closed fleet result`, () => { const result = qualifyFleet(scenarios[name]); assert.equal(result.decision, decision); if (reason !== 'REHEARSAL') assert.ok(result.reasonCodes.includes(reason)); assert.equal(result.dependencies.failClosed, true); assert.equal(result.observations.confidentialGuestsObserved, 0); assert.equal(result.observations.currentTdxQuotesVerified, 0); assert.equal(result.observations.protectedResourcesReleased, 0); assert.equal(result.observations.modelExecutions, 0) })
test('baseline correlates every node but grants no promotion authority', () => { const result = qualifyFleet(scenarios.baseline); assert.deepEqual(result.evidence.correlatedNodes, ['tdx-a', 'tdx-b', 'tdx-c']); assert.match(result.evidence.receipt, /^sha256:[a-f0-9]{64}$/); assert.deepEqual(result.authority, {humanPromotionRequired: true, mayCertify: false, mayPromote: false, mayPublish: false, maxWorkshopSeats: 0, llmAuthority: 'NONE'}) })
test('capacity refusal admits only the declared rehearsal limit', () => { const result = qualifyFleet(scenarios.capacity_exceeded); assert.equal(result.capacity.requested, 18); assert.equal(result.capacity.admitted, 12); assert.equal(result.capacity.refused, 6); assert.equal(result.capacity.measuredLive, false) })
test('malformed evidence fails closed', () => { const result = qualifyFleet({}); assert.equal(result.decision, 'REFUSE_PROMOTION'); assert.ok(result.reasonCodes.includes('INSUFFICIENT_FLEET_EVIDENCE')) })
