apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-presentation
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}-presentation
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
