apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: story
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}-presentation
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fleet
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}-qualifier
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
