FROM cgr.dev/chainguard/wolfi-base@sha256:82d42999b1bc4b2aa724b442d300194901e64563efec75b3245e41f4c09fb6d2
RUN apk add --no-cache nodejs-22-minimal
WORKDIR /app
COPY workload/ ./workload/
USER 65532
EXPOSE 8080
CMD ["/usr/bin/node", "workload/server.mjs"]
