sourceState: REHEARSAL
images:
  presentation:
    repository: ghcr.io/jkershawrh/sovereign-ai-501-presentation
    digest: sha256:cd739547778feaaa5c0d86af26032a1b5962e95fe5447ec0b477730020daae64
  qualifier:
    repository: ghcr.io/jkershawrh/sovereign-ai-501-qualifier
    digest: sha256:cc3b3cfc19697b57d03347491523b6d72524fdb7890c591344ca714bbc4bca57
imagePullPolicy: IfNotPresent
presentation:
  replicas: 1
  resources:
    requests: {cpu: 25m, memory: 32Mi}
    limits: {cpu: 250m, memory: 128Mi}
qualifier:
  replicas: 1
  resources:
    requests: {cpu: 25m, memory: 48Mi}
    limits: {cpu: 250m, memory: 128Mi}
confidentialRuntime:
  enabled: false
  runtimeClassName: ""
networkPolicy:
  enabled: true
  ingressNamespaceSelector: {}
